# Generated by Django 6.0.3 on 2026-03-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_bookmark_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created_at"]},
        ),
    ]
