# Generated by Django 6.0.3 on 2026-03-18 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0003_alter_bookmark_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(fields=["name"], name="bookmarks_b_name_0da4f1_idx"),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["created_at"], name="bookmarks_b_created_ba7fa0_idx"
            ),
        ),
    ]
